language: elixir
elixir:
  - 1.4.0
  
otp_release:
  - 19.1

script:
  - mix test
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)
